# -*- coding: utf-8 -*-
"""Copy of Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N2HDpNBYEwnHPVMhwxKFfJhA8ER3NiDa

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

str="Hi how are you"
print(str.split())

"""*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

planet = "Earth"
diameter = 12742
a="The diameter of {planet}is{diameter}kilometers"
print(a.format(planet="Earth",diameter = 12742))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':
[1,2,3,'hello']}]}]}
print(d)

"""# Numpy"""



"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
b=np.zeros(10)*0
print(b)

b=np.ones(10)*5
print(b)

"""## 5. Create an array of all the even integers from 20 to 35"""

ar=np.arange(20,35,2)
print(ar)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

a=np.arange(0,9).reshape(3,3)
print(a)

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd
data=[{'a':12,'b':45},{'a':54,'b':23},{'a':94,'b':76}]
df=pd.DataFrame(data)
print(df)



"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

a=pd.date_range(start='1/1/2023',end='10/2/2023')
print(a)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lst=[[1,'aaa',22],[2,'bbb,25'],[3,'ccc',24]]
df=pd.DataFrame(lst)
print(df)

